{
  "id": "/questions/2069254",
  "creationDate": "2014-01-17T19:19:09.943",
  "body": "\n\n**Base project structure**\n\n\tbaseproject\n\t    baseapp\n\t        models.py\n\t            class BaseModel(models.Model)\n\t            ...\n\t\n\n**Other project structure**:\n\n\tproject\n\t    app\n\t        views.py\n\t        urls.py\n\t\n\n**project.app.views.py**\n\n\timport os\n\tos.environ['DJANGO_SETTINGS_MODULE'] = 'project.settings'\n\tfrom django.conf import settings\n\tfrom baseproject.baseapp.models import BaseModel\n\tprint BaseModel.objects.count()\n\t\n\nit raised \"Table 'project.baseapp_baemodel' doesn't exist\" error when run from command line: \"python views.py\".\n\n\timport os\n\tos.environ['DJANGO_SETTINGS_MODULE'] = 'baseproject.settings'\n\tfrom django.conf import settings\n\tfrom baseproject.baseapp.models import BaseModel\n\tprint BaseModel.objects.count()\n\t\n\nAfter changed project.settings to baseproject.settings, it works in command line.\n\n\timport os\n\tos.environ['DJANGO_SETTINGS_MODULE'] = 'baseproject.settings'\n\tfrom django.conf import settings\n\tfrom baseproject.baseapp.models import BaseModel\n\t\n\tdef someview(request):\n\t    count = BaseModel.objects.count()\n\t    return render_to_response(...)\n\t\n\nBut it still raised \"Table 'project.baseapp_baemodel' doesn't exist\" error when access the view by opening corresponding url in browser.\n\nWhat's wrong in above code?",
  "lastActivityDate": "2014-01-18T06:07:15.583",
  "title": "Access models in other project in a Django view cause \"table doesn't exist\" error",
  "tags": [
    "python",
    "django",
    "model"
  ],
  "docScore": 0,
  "comments": [],
  "answers": [],
  "creationYearMonth": "201401",
  "itemTally": 0,
  "owner": null
}